### ISSUE TITLE
transpose project from Java to kotlin/Api 28/AndroidX

### ISSUE THREAD

**Issue by neuberfran** [neuberfran/FirebaseArcCompB#1]
Hi,

I stay transpose this project from JAVA to KOTLIN and I have issues:

**original project 👍** 
https://github.com/SinanYilmaz9/FirebaseArcComp?source=post_page---------------------------

**project working in JAVA by me:**
https://github.com/neuberfran/FirebaseArcComp

issues:
![erro1](https://user-images.githubusercontent.com/38701397/62010208-9f38a100-b11c-11e9-97e1-dc6b5b3c316c.png)

![erro2](https://user-images.githubusercontent.com/38701397/62010215-a6f84580-b11c-11e9-803a-e1b0d329881c.png)

**Comment by AhmadAyyaz1993** [comment]
can you please post your complete error log?

**Comment by AhmadAyyaz1993** [comment]
there are some issues with your models Message.kt and Entity.kt

**Comment by AhmadAyyaz1993** [comment]
make your models like this
object TokenHelper {
    var token: String? = null
    var appId: String? = null
    var installationId: String? = null
    var userId: String? = null
}

**Comment by neuberfran** [comment]
Not solved, cannot inherity from a singleton:

![Captura de Tela 2019-08-04 às 17 27 36](https://user-images.githubusercontent.com/38701397/62431563-4dc08100-b6dd-11e9-9228-a9efa86d7dc8.png)

![Captura de Tela 2019-08-04 às 17 27 10](https://user-images.githubusercontent.com/38701397/62431567-54e78f00-b6dd-11e9-8be0-822f59337b4d.png)

**Comment by AhmadAyyaz1993** [comment]
change your Message class from object to data class like Entity.kt

**Comment by neuberfran** [comment]
**climbed the screen but at the time of authentication:**

2019-08-10 20:13:05.079 5684-5710/? E/libprocessgroup: Error encountered killing process cgroup uid 10150 pid 4332: No such file or directory
2019-08-10 20:13:05.097 4807-4807/app.sinanyilmaz.firebasearccomp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.sinanyilmaz.firebasearccomp, PID: 4807
    java.lang.StackOverflowError: stack size 8MB
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
2019-08-10 20:13:05.098 4807-4807/app.sinanyilmaz.firebasearccomp E/AndroidRuntime:     at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
2019-08-10 20:13:05.184 7324-7324/? E/SPPClientService: [PackageInfoChangeReceiver] android.intent.action.PACKAGE_REMOVED
2019-08-10 20:13:05.184 7324-7324/? E/SPPClientService: [PackageInfoChangeReceiver] [handlePkgRemovedEvent] PackageName : flipboard.boxer.app, true, false
2019-08-10 20:13:05.184 7324-7324/? E/SPPClientService: [PackageInfoChangeReceiver] [handlePkgRemovedEvent] Ignore Replacing case
2019-08-10 20:13:05.195 2372-2462/? E/AASAservice-TokenRule: parseToken() : TokenFile is null
2019-08-10 20:13:05.196 5684-6384/? E/AASATokenParser: set xml file does not exist
2019-08-10 20:13:05.199 2372-2462/? E/AASAservice-IntentThread: AASAIntentThread : myrule is null.
2019-08-10 20:13:05.243 4807-4807/app.sinanyilmaz.firebasearccomp E/AndroidRuntime:     at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
2019-08-10 20:13:05.243 4807-4807/app.sinanyilmaz.firebasearccomp E/AndroidRuntime:     at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.data.Entity.getPhotoUrl(Entity.kt:13)
        at app.sinanyilmaz.firebasearccomp.ui.MessageAdapter.onBindViewHolder(MessageAdapter.kt:43)
        at app.sinanyilmaz.firebasearccomp.ui.MessageAdapter.onBindViewHolder(MessageAdapter.kt:18)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:4082)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.support.design.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1191)
        at android.support.design.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:876)
        at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:895)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
2019-08-10 20:13:05.243 4807-4807/app.sinanyilmaz.firebasearccomp E/AndroidRuntime:     at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.support.v7.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:443)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1041)
        at android.view.View.layout(View.java:22426)
        at android.view.ViewGroup.layout(ViewGroup.java:6584)
        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3366)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2830)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1876)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8499)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7037)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by neuberfran** [comment]
![Captura de Tela 2019-08-10 às 20 18 33](https://user-images.githubusercontent.com/38701397/62829147-143fb800-bbac-11e9-9473-b17674fb0527.png)
